package UserInterface.Login;

import Function.Image.FitImage;
import Function.SeeAndUnseePass.SeeAndUnseePass;
import Function.file.file;
import java.awt.Color;
import Function.textField.txtField;
import Function.password.checkPasswordField;
import Model.UserData.UserData;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class SignIn extends javax.swing.JFrame {

    public ArrayList<UserData> data = new ArrayList<UserData>();
    private File profile = null;
    private static final txtField txtfield = new txtField();
    private static final checkPasswordField chckpass = new checkPasswordField();
    private static final SeeAndUnseePass chckbox = new SeeAndUnseePass();
    private UserData user = new UserData();
    public int userDataIndex = -1;

    private void login() {
        String pass = String.valueOf(txtpassword.getPassword());
        if (pass.equals("Password") || txtusername.getText().equals("Username")) {
            JOptionPane.showMessageDialog(this, "Invalid Username and PAssword ", "NO Data Found", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        userDataIndex = user.userLogin(data, txtusername.getText(), pass);
        if (userDataIndex == -1) {
            JOptionPane.showMessageDialog(this, "No Data Of Username Found ", "NO Data Found", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        this.setVisible(false);
        this.txtusername.setText("");
        this.txtpassword.setText("");

    }

    private void SignUp() {

        String SignupPass = String.valueOf(this.txtpasswordSignup1.getPassword());
        String confirmPass = String.valueOf(this.txtconfirmpasswordSignup.getPassword());
        String usernameSignup = txtusernameSignUp.getText();
        String lastName = txtlastname.getText();
        String firstName = txtfirstname.getText();
        if (cbgender.getSelectedItem().equals("Gender")
                || lastName.isEmpty()
                || lastName.equals("LastName")
                || firstName.equals("LastName")
                || firstName.isEmpty()
                || usernameSignup.isEmpty()
                || usernameSignup.equals("Username")
                || SignupPass.equals("Password")
                || SignupPass.isEmpty()
                || confirmPass.equals("Confirm Password")
                || confirmPass.isEmpty()
                || datePicker2.getText().isEmpty()
                || !chckpass.isConfirmPassAndPassSame(SignupPass, confirmPass)) {
            JOptionPane.showMessageDialog(this, "Invalid SignUp Fill Up EveryThing ", "Invalid SignUP",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        data.add(new UserData(data, usernameSignup, SignupPass, firstName, lastName, profile, datePicker2.getText()));
    }

    public SignIn() {
        initComponents();
        txtpassword.setEchoChar((char) 0);
        chckseeUnsee.setVisible(false);
        txtpasswordSignup1.setEchoChar((char) 0);
        txtconfirmpasswordSignup.setEchoChar((char) 0);
        chckseeUnseeConfirmPassSignup.setVisible(false);
        chckseeUnseeSignup1.setVisible(false);
        datePicker2.getComponentDateTextField().setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabLogInOut = new javax.swing.JTabbedPane();
        signIn = new UserInterface.CustomComponents.MyPanel();
        btnsignIn = new UserInterface.CustomComponents.MyButton();
        chckseeUnsee = new javax.swing.JCheckBox();
        txtpassword = new UserInterface.CustomComponents.MyPasswordField();
        txtusername = new UserInterface.CustomComponents.MyTextField();
        jLabel1 = new javax.swing.JLabel();
        signUp = new UserInterface.CustomComponents.MyPanel();
        txtlastname = new UserInterface.CustomComponents.MyTextField();
        txtfirstname = new UserInterface.CustomComponents.MyTextField();
        chckseeUnseeConfirmPassSignup = new javax.swing.JCheckBox();
        chckseeUnseeSignup1 = new javax.swing.JCheckBox();
        txtusernameSignUp = new UserInterface.CustomComponents.MyTextField();
        txtconfirmpasswordSignup = new UserInterface.CustomComponents.MyPasswordField();
        txtpasswordSignup1 = new UserInterface.CustomComponents.MyPasswordField();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        btnSignUp = new UserInterface.CustomComponents.MyButton();
        myButton1 = new UserInterface.CustomComponents.MyButton();
        lblPictureHolder = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        myRainingTetroAnimation1 = new UserInterface.CustomComponents.MyRainingTetroAnimation(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setBackground(new java.awt.Color(0, 255, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signIn.setBackground(new java.awt.Color(0, 153, 0));
        signIn.setBottomLeftRadius(150);
        signIn.setBottomRightRadius(0);
        signIn.setInnerColor(new java.awt.Color(255, 255, 255));
        signIn.setName("SignInPanel"); // NOI18N
        signIn.setTopLeftRadius(150);
        signIn.setTopRightRadius(0);
        signIn.setLayout(null);

        btnsignIn.setText("SignIn");
        btnsignIn.setToolTipText("");
        btnsignIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsignIn.setName("btnSignUp"); // NOI18N
        btnsignIn.setNextFocusableComponent(jLabel1);
        btnsignIn.setRadius(50);
        btnsignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignInActionPerformed(evt);
            }
        });
        signIn.add(btnsignIn);
        btnsignIn.setBounds(70, 352, 235, 46);
        btnsignIn.getAccessibleContext().setAccessibleName("");

        chckseeUnsee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnsee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeActionPerformed(evt);
            }
        });
        signIn.add(chckseeUnsee);
        chckseeUnsee.setBounds(270, 270, 24, 20);

        txtpassword.setText("Password");
        txtpassword.setCornerRadius(50);
        txtpassword.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        txtpassword.setName("txtpassword"); // NOI18N
        txtpassword.setNextFocusableComponent(btnsignIn);
        txtpassword.setToolTipText("");
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        signIn.add(txtpassword);
        txtpassword.setBounds(70, 249, 235, 54);

        txtusername.setText("Username");
        txtusername.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/username.png"))); // NOI18N
        txtusername.setName("txtusername"); // NOI18N
        txtusername.setNextFocusableComponent(txtpassword);
        txtusername.setRadius(50);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        signIn.add(txtusername);
        txtusername.setBounds(70, 146, 235, 54);
        txtusername.getAccessibleContext().setAccessibleName("txtusername");

        jLabel1.setText("Havent Had AccountYet?");
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        signIn.add(jLabel1);
        jLabel1.setBounds(109, 404, 157, 17);

        tabLogInOut.addTab("tab1", signIn);

        signUp.setBackground(new java.awt.Color(0, 153, 0));
        signUp.setBottomLeftRadius(150);
        signUp.setBottomRightRadius(0);
        signUp.setName("SignUpPanel"); // NOI18N
        signUp.setTopLeftRadius(150);
        signUp.setTopRightRadius(0);
        signUp.setLayout(null);

        txtlastname.setText("LastName");
        txtlastname.setRadius(50);
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });
        txtlastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastnameMouseClicked(evt);
            }
        });
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        signUp.add(txtlastname);
        txtlastname.setBounds(180, 310, 140, 50);

        txtfirstname.setText("FirstName");
        txtfirstname.setRadius(50);
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfirstnameMouseClicked(evt);
            }
        });
        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });
        signUp.add(txtfirstname);
        txtfirstname.setBounds(40, 310, 130, 50);

        chckseeUnseeConfirmPassSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnseeConfirmPassSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeConfirmPassSignupActionPerformed(evt);
            }
        });
        signUp.add(chckseeUnseeConfirmPassSignup);
        chckseeUnseeConfirmPassSignup.setBounds(290, 270, 24, 20);

        chckseeUnseeSignup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnseeSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeSignup1ActionPerformed(evt);
            }
        });
        signUp.add(chckseeUnseeSignup1);
        chckseeUnseeSignup1.setBounds(290, 210, 24, 20);

        txtusernameSignUp.setText("Username");
        txtusernameSignUp.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/username.png"))); // NOI18N
        txtusernameSignUp.setName("txtusername"); // NOI18N
        txtusernameSignUp.setRadius(50);
        txtusernameSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameSignUpFocusLost(evt);
            }
        });
        txtusernameSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameSignUpMouseClicked(evt);
            }
        });
        txtusernameSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameSignUpActionPerformed(evt);
            }
        });
        signUp.add(txtusernameSignUp);
        txtusernameSignUp.setBounds(40, 120, 290, 54);

        txtconfirmpasswordSignup.setText("Confirm Password");
        txtconfirmpasswordSignup.setCornerRadius(50);
        txtconfirmpasswordSignup.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        txtconfirmpasswordSignup.setName("txtpassword"); // NOI18N
        txtconfirmpasswordSignup.setToolTipText("");
        txtconfirmpasswordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmpasswordSignupFocusLost(evt);
            }
        });
        txtconfirmpasswordSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtconfirmpasswordSignupMouseClicked(evt);
            }
        });
        txtconfirmpasswordSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmpasswordSignupActionPerformed(evt);
            }
        });
        txtconfirmpasswordSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordSignupKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconfirmpasswordSignupKeyReleased(evt);
            }
        });
        signUp.add(txtconfirmpasswordSignup);
        txtconfirmpasswordSignup.setBounds(40, 250, 290, 54);

        txtpasswordSignup1.setText("Password");
        txtpasswordSignup1.setCornerRadius(50);
        txtpasswordSignup1.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        txtpasswordSignup1.setName("txtpassword"); // NOI18N
        txtpasswordSignup1.setToolTipText("");
        txtpasswordSignup1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordSignup1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordSignup1FocusLost(evt);
            }
        });
        txtpasswordSignup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordSignup1MouseClicked(evt);
            }
        });
        txtpasswordSignup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordSignup1ActionPerformed(evt);
            }
        });
        txtpasswordSignup1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordSignup1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordSignup1KeyReleased(evt);
            }
        });
        signUp.add(txtpasswordSignup1);
        txtpasswordSignup1.setBounds(40, 190, 290, 54);

        datePicker2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        signUp.add(datePicker2);
        datePicker2.setBounds(130, 390, 200, 50);

        btnSignUp.setText("SignUp");
        btnSignUp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSignUp.setRadius(50);
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        signUp.add(btnSignUp);
        btnSignUp.setBounds(110, 460, 200, 50);

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic.png"))); // NOI18N
        myButton1.setBorderColor(new java.awt.Color(0, 0, 255));
        myButton1.setIconTextGap(0);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        signUp.add(myButton1);
        myButton1.setBounds(200, 70, 42, 42);

        lblPictureHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        signUp.add(lblPictureHolder);
        lblPictureHolder.setBounds(140, 20, 100, 90);

        jLabel2.setText("Already Have Account?");
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        signUp.add(jLabel2);
        jLabel2.setBounds(140, 510, 147, 20);

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));
        cbgender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgenderItemStateChanged(evt);
            }
        });
        cbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenderActionPerformed(evt);
            }
        });
        signUp.add(cbgender);
        cbgender.setBounds(40, 390, 80, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BOD(BIRTH OF DATE):");
        signUp.add(jLabel3);
        jLabel3.setBounds(130, 370, 200, 17);

        tabLogInOut.addTab("tab1", signUp);

        getContentPane().add(tabLogInOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -40, 350, 570));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout myRainingTetroAnimation1Layout = new javax.swing.GroupLayout(myRainingTetroAnimation1);
        myRainingTetroAnimation1.setLayout(myRainingTetroAnimation1Layout);
        myRainingTetroAnimation1Layout.setHorizontalGroup(
            myRainingTetroAnimation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        myRainingTetroAnimation1Layout.setVerticalGroup(
            myRainingTetroAnimation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myRainingTetroAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(myRainingTetroAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        login();
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        tabLogInOut.setSelectedIndex(1);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void chckseeUnseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeActionPerformed
        chckbox.unseeAndseeIconChange(chckseeUnsee, txtpassword);
    }//GEN-LAST:event_chckseeUnseeActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        chckpass.HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        chckpass.HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
        txtfield.checkTextField(txtusername, "Username");
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        txtfield.checkTextField(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        txtfield.checkTextFieldEmpty(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        chckpass.HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        chckpass.FocusLostPass(txtpassword, "Password");
    }//GEN-LAST:event_txtpasswordFocusLost

    private void chckseeUnseeSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeSignup1ActionPerformed
        chckbox.unseeAndseeIconChange(chckseeUnseeSignup1, txtpasswordSignup1);
    }//GEN-LAST:event_chckseeUnseeSignup1ActionPerformed

    private void txtusernameSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameSignUpFocusGained
        txtfield.checkTextField(txtusernameSignUp, "Username");
    }//GEN-LAST:event_txtusernameSignUpFocusGained

    private void txtusernameSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameSignUpFocusLost
        txtfield.checkTextFieldEmpty(txtusernameSignUp, "Username");
    }//GEN-LAST:event_txtusernameSignUpFocusLost

    private void txtusernameSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameSignUpMouseClicked
        txtfield.checkTextField(txtusernameSignUp, "Username");
    }//GEN-LAST:event_txtusernameSignUpMouseClicked

    private void txtpasswordSignup1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordSignup1FocusGained
        chckpass.HoverAndClickPassword(txtpasswordSignup1, chckseeUnseeSignup1, "Password");
    }//GEN-LAST:event_txtpasswordSignup1FocusGained

    private void txtpasswordSignup1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordSignup1FocusLost
        chckpass.FocusLostPass(txtpasswordSignup1, "Password");
    }//GEN-LAST:event_txtpasswordSignup1FocusLost

    private void txtpasswordSignup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordSignup1MouseClicked
        chckpass.HoverAndClickPassword(txtpasswordSignup1, chckseeUnseeSignup1, "Password");
    }//GEN-LAST:event_txtpasswordSignup1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.tabLogInOut.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new Color(0, 51, 255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(new Color(0, 153, 255));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel2.setForeground(new Color(51, 0, 255));
    }//GEN-LAST:event_jLabel1MouseExited

    private void cbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenderActionPerformed

    }//GEN-LAST:event_cbgenderActionPerformed

    private void txtconfirmpasswordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupFocusGained
        chckpass.HoverAndClickPassword(txtconfirmpasswordSignup, chckseeUnseeConfirmPassSignup, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordSignupFocusGained

    private void txtconfirmpasswordSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupFocusLost
        chckpass.FocusLostPass(txtconfirmpasswordSignup, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordSignupFocusLost

    private void txtconfirmpasswordSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupMouseClicked
        chckpass.HoverAndClickPassword(txtconfirmpasswordSignup, chckseeUnseeConfirmPassSignup, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordSignupMouseClicked

    private void chckseeUnseeConfirmPassSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeConfirmPassSignupActionPerformed
        chckbox.unseeAndseeIconChange(chckseeUnseeConfirmPassSignup, txtconfirmpasswordSignup);
    }//GEN-LAST:event_chckseeUnseeConfirmPassSignupActionPerformed

    private void cbgenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbgenderItemStateChanged
        if (!cbgender.equals("Gender")) {
            cbgender.removeItem("Gender");
        }
        new file().FileCheckGender(profile, cbgender, lblPictureHolder);
    }//GEN-LAST:event_cbgenderItemStateChanged

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        profile = new file().FilePictureFilter(profile);
        if (profile != null) {
            new FitImage().risizelabel(profile, lblPictureHolder);
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void txtpasswordSignup1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordSignup1KeyPressed
        chckpass.HoverAndClickPassword(txtpasswordSignup1, chckseeUnseeSignup1, "Password");
    }//GEN-LAST:event_txtpasswordSignup1KeyPressed

    private void txtpasswordSignup1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordSignup1KeyReleased
        chckpass.HoverAndClickPassword(txtpasswordSignup1, chckseeUnseeSignup1, "Password");
    }//GEN-LAST:event_txtpasswordSignup1KeyReleased

    private void txtconfirmpasswordSignupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupKeyPressed
        chckpass.HoverAndClickPassword(txtconfirmpasswordSignup, this.chckseeUnseeConfirmPassSignup, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordSignupKeyPressed

    private void txtconfirmpasswordSignupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupKeyReleased
        chckpass.HoverAndClickPassword(txtconfirmpasswordSignup, this.chckseeUnseeConfirmPassSignup, "Confirm Password");
    }//GEN-LAST:event_txtconfirmpasswordSignupKeyReleased

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusGained
        txtfield.checkTextField(txtfirstname, "FirstName");
    }//GEN-LAST:event_txtfirstnameFocusGained

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfirstnameFocusLost
        txtfield.checkTextFieldEmpty(txtfirstname, "FirstName");
    }//GEN-LAST:event_txtfirstnameFocusLost

    private void txtfirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfirstnameMouseClicked
        txtfield.checkTextField(txtfirstname, "FirstName");
    }//GEN-LAST:event_txtfirstnameMouseClicked

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusGained
        txtfield.checkTextField(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameFocusGained

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtlastnameFocusLost
        txtfield.checkTextFieldEmpty(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameFocusLost

    private void txtlastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlastnameMouseClicked
        txtfield.checkTextField(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameMouseClicked

    private void txtusernameSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameSignUpActionPerformed
        SignUp();
    }//GEN-LAST:event_txtusernameSignUpActionPerformed

    private void btnsignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignInActionPerformed
        login();
    }//GEN-LAST:event_btnsignInActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        login();
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        SignUp();

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtpasswordSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordSignup1ActionPerformed
        SignUp();
    }//GEN-LAST:event_txtpasswordSignup1ActionPerformed

    private void txtconfirmpasswordSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmpasswordSignupActionPerformed
        SignUp();
    }//GEN-LAST:event_txtconfirmpasswordSignupActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        SignUp();
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        SignUp();
    }//GEN-LAST:event_txtlastnameActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UserInterface.CustomComponents.MyButton btnSignUp;
    private UserInterface.CustomComponents.MyButton btnsignIn;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JCheckBox chckseeUnsee;
    private javax.swing.JCheckBox chckseeUnseeConfirmPassSignup;
    private javax.swing.JCheckBox chckseeUnseeSignup1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPictureHolder;
    private UserInterface.CustomComponents.MyButton myButton1;
    private UserInterface.CustomComponents.MyRainingTetroAnimation myRainingTetroAnimation1;
    private UserInterface.CustomComponents.MyPanel signIn;
    private UserInterface.CustomComponents.MyPanel signUp;
    private javax.swing.JTabbedPane tabLogInOut;
    private UserInterface.CustomComponents.MyPasswordField txtconfirmpasswordSignup;
    private UserInterface.CustomComponents.MyTextField txtfirstname;
    private UserInterface.CustomComponents.MyTextField txtlastname;
    private UserInterface.CustomComponents.MyPasswordField txtpassword;
    private UserInterface.CustomComponents.MyPasswordField txtpasswordSignup1;
    private UserInterface.CustomComponents.MyTextField txtusername;
    private UserInterface.CustomComponents.MyTextField txtusernameSignUp;
    // End of variables declaration//GEN-END:variables
}
