/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.settings;

import Function.textField.txtField;
import Model.UserData.UserData;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTextField;

public class Settings extends javax.swing.JPanel {

    private ArrayList<UserData> data;
    private int index;

    private void userPressKey(ArrayList<UserData> data, int userIndex, JTextField text, String keyName, KeyEvent e) {
        int vkCode = e.getKeyCode();
        String nameKeyPress = KeyEvent.getKeyText(vkCode);
        UserData da = data.get(userIndex);

        da.updateUserKeyBinds(keyName, vkCode);
        text.setText(nameKeyPress);

    }
    
    private void loaduserSettings(){
        UserData da = data.get(index);
        txtleft.setText(da.getStringUserKeyBinds("MOVE_LEFT"));
        txtdown.setText(da.getStringUserKeyBinds("MOVE_DOWN"));
        txtright.setText(da.getStringUserKeyBinds("MOVE_RIGHT"));
        txtrotate.setText(da.getStringUserKeyBinds("ROTATE"));
        txtHardDrop.setText(da.getStringUserKeyBinds("HARD_DROP"));
    }

    public Settings(ArrayList<UserData> data, int index) {
        initComponents();
        this.data = data;
        this.index = index;
        loaduserSettings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdown = new UserInterface.CustomComponents.MyTextField();
        txtleft = new UserInterface.CustomComponents.MyTextField();
        jLabel2 = new javax.swing.JLabel();
        txtright = new UserInterface.CustomComponents.MyTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrotate = new UserInterface.CustomComponents.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHardDrop = new UserInterface.CustomComponents.MyTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(621, 570));

        jLabel1.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Move Down:");

        txtdown.setEditable(false);
        txtdown.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtdown.setRadius(50);
        txtdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdownActionPerformed(evt);
            }
        });
        txtdown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdownKeyPressed(evt);
            }
        });

        txtleft.setEditable(false);
        txtleft.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtleft.setRadius(50);
        txtleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtleftActionPerformed(evt);
            }
        });
        txtleft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtleftKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Move Left:");

        txtright.setEditable(false);
        txtright.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtright.setRadius(50);
        txtright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrightActionPerformed(evt);
            }
        });
        txtright.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrightKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Move Right:");

        txtrotate.setEditable(false);
        txtrotate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtrotate.setRadius(50);
        txtrotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrotateActionPerformed(evt);
            }
        });
        txtrotate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrotateKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rotate:");

        txtHardDrop.setEditable(false);
        txtHardDrop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtHardDrop.setRadius(50);
        txtHardDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHardDropActionPerformed(evt);
            }
        });
        txtHardDrop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHardDropKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hard Drop:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtdown, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtleft, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtright, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtrotate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addComponent(txtHardDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtleft, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtright, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtrotate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHardDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdownActionPerformed
    }//GEN-LAST:event_txtdownActionPerformed

    private void txtleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtleftActionPerformed
    }//GEN-LAST:event_txtleftActionPerformed

    private void txtrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrightActionPerformed
    }//GEN-LAST:event_txtrightActionPerformed

    private void txtrotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrotateActionPerformed
    }//GEN-LAST:event_txtrotateActionPerformed

    private void txtHardDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHardDropActionPerformed
    }//GEN-LAST:event_txtHardDropActionPerformed

    private void txtdownKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdownKeyPressed
        userPressKey(data, index, txtdown, "MOVE_DOWN", evt);
    }//GEN-LAST:event_txtdownKeyPressed

    private void txtleftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtleftKeyPressed
        userPressKey(data, index, txtleft, "MOVE_LEFT", evt);
    }//GEN-LAST:event_txtleftKeyPressed

    private void txtrightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrightKeyPressed
        userPressKey(data, index, txtright, "MOVE_RIGHT", evt);
    }//GEN-LAST:event_txtrightKeyPressed

    private void txtrotateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrotateKeyPressed
        userPressKey(data, index, txtrotate, "ROTATE", evt);

    }//GEN-LAST:event_txtrotateKeyPressed

    private void txtHardDropKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHardDropKeyPressed
        userPressKey(data, index, txtHardDrop, "HARD_DROP", evt);
    }//GEN-LAST:event_txtHardDropKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private UserInterface.CustomComponents.MyTextField txtHardDrop;
    private UserInterface.CustomComponents.MyTextField txtdown;
    private UserInterface.CustomComponents.MyTextField txtleft;
    private UserInterface.CustomComponents.MyTextField txtright;
    private UserInterface.CustomComponents.MyTextField txtrotate;
    // End of variables declaration//GEN-END:variables
}
