/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.settings;

import Function.textField.txtField;

/**
 *
 * @author Admin
 */
public class settings extends javax.swing.JPanel {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtdown = new UserInterface.CustomComponents.MyTextField();
        txtleft = new UserInterface.CustomComponents.MyTextField();
        jLabel2 = new javax.swing.JLabel();
        txtright = new UserInterface.CustomComponents.MyTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrotate = new UserInterface.CustomComponents.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHardDrop = new UserInterface.CustomComponents.MyTextField();
        jLabel5 = new javax.swing.JLabel();
        btnsaveSetting = new UserInterface.CustomComponents.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(621, 570));

        jLabel1.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Move Down:");

        txtdown.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtdown.setRadius(50);
        txtdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdownActionPerformed(evt);
            }
        });

        txtleft.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtleft.setRadius(50);
        txtleft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtleftActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Move Left:");

        txtright.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtright.setRadius(50);
        txtright.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrightActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Move Right:");

        txtrotate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtrotate.setRadius(50);
        txtrotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrotateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rotate:");

        txtHardDrop.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtHardDrop.setRadius(50);
        txtHardDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHardDropActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hard Drop:");

        btnsaveSetting.setText("Save Setting");
        btnsaveSetting.setFont(new java.awt.Font("Retro Gaming", 1, 18)); // NOI18N
        btnsaveSetting.setRadius(50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txtdown, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txtleft, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtright, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtrotate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(17, 17, 17)
                .addComponent(txtHardDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(btnsaveSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtdown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtleft, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtright, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtrotate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtHardDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addComponent(btnsaveSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdownActionPerformed
        new txtField().getTheKeyText(txtdown);
    }//GEN-LAST:event_txtdownActionPerformed

    private void txtleftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtleftActionPerformed
        new txtField().getTheKeyText(txtleft);
    }//GEN-LAST:event_txtleftActionPerformed

    private void txtrightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrightActionPerformed
        new txtField().getTheKeyText(txtright);
    }//GEN-LAST:event_txtrightActionPerformed

    private void txtrotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrotateActionPerformed
        new txtField().getTheKeyText(txtrotate);
    }//GEN-LAST:event_txtrotateActionPerformed

    private void txtHardDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHardDropActionPerformed
        new txtField().getTheKeyText(txtHardDrop);
    }//GEN-LAST:event_txtHardDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UserInterface.CustomComponents.MyButton btnsaveSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private UserInterface.CustomComponents.MyTextField txtHardDrop;
    private UserInterface.CustomComponents.MyTextField txtdown;
    private UserInterface.CustomComponents.MyTextField txtleft;
    private UserInterface.CustomComponents.MyTextField txtright;
    private UserInterface.CustomComponents.MyTextField txtrotate;
    // End of variables declaration//GEN-END:variables
}
