/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.Admin;

public class Account extends javax.swing.JFrame {

    File profile = null;
    
    public Account() {
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chckseeUnsee = new javax.swing.JCheckBox();
        myButton1 = new UserInterface.CustomComponents.MyButton();
        btndelete = new UserInterface.CustomComponents.MyButton();
        txtlastname = new UserInterface.CustomComponents.MyTextField();
        txtusername = new UserInterface.CustomComponents.MyTextField();
        txtfirstname = new UserInterface.CustomComponents.MyTextField();
        myButton2 = new UserInterface.CustomComponents.MyButton();
        btnban = new UserInterface.CustomComponents.MyButton();
        btnupdate = new UserInterface.CustomComponents.MyButton();
        lblpictureHolder = new javax.swing.JLabel();
        cbgender = new javax.swing.JComboBox<>();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        txtpassword = new UserInterface.CustomComponents.MyPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable1 = new UserInterface.CustomComponents.MyTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(621, 570));
        jPanel1.setLayout(null);

        chckseeUnsee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnsee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeActionPerformed(evt);
            }
        });
        jPanel1.add(chckseeUnsee);
        chckseeUnsee.setBounds(580, 280, 24, 20);

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic.png"))); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton1);
        myButton1.setBounds(129, 380, 50, 50);

        btndelete.setText("Delete Account");
        btndelete.setBorderColor(new java.awt.Color(255, 0, 0));
        btndelete.setColor(new java.awt.Color(255, 0, 0));
        btndelete.setColorClick(new java.awt.Color(255, 51, 51));
        btndelete.setColorOver(new java.awt.Color(255, 102, 102));
        btndelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndelete.setRadius(50);
        jPanel1.add(btndelete);
        btndelete.setBounds(180, 530, 100, 30);

        txtlastname.setText("LastName");
        txtlastname.setRadius(50);
        txtlastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastnameMouseClicked(evt);
            }
        });
        txtlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlastnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlastnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtlastname);
        txtlastname.setBounds(410, 330, 200, 40);

        txtusername.setText("Username");
        txtusername.setRadius(50);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        jPanel1.add(txtusername);
        txtusername.setBounds(190, 270, 200, 40);

        txtfirstname.setText("FirstName");
        txtfirstname.setRadius(50);
        txtfirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfirstnameMouseClicked(evt);
            }
        });
        txtfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfirstnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtfirstname);
        txtfirstname.setBounds(190, 330, 200, 40);

        myButton2.setText("Add Account");
        myButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        myButton2.setRadius(50);
        jPanel1.add(myButton2);
        myButton2.setBounds(520, 530, 100, 30);

        btnban.setText("Ban Account");
        btnban.setBorderColor(new java.awt.Color(255, 102, 0));
        btnban.setColor(new java.awt.Color(255, 102, 0));
        btnban.setColorClick(new java.awt.Color(255, 204, 51));
        btnban.setColorOver(new java.awt.Color(255, 204, 102));
        btnban.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnban.setRadius(50);
        jPanel1.add(btnban);
        btnban.setBounds(290, 530, 100, 30);

        btnupdate.setText("Update Account");
        btnupdate.setBorderColor(new java.awt.Color(102, 204, 0));
        btnupdate.setColor(new java.awt.Color(102, 204, 0));
        btnupdate.setColorClick(new java.awt.Color(153, 255, 51));
        btnupdate.setColorOver(new java.awt.Color(153, 255, 102));
        btnupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnupdate.setRadius(50);
        jPanel1.add(btnupdate);
        btnupdate.setBounds(400, 530, 100, 30);

        lblpictureHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblpictureHolder);
        lblpictureHolder.setBounds(10, 260, 170, 170);

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", " " }));
        cbgender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbgenderMouseClicked(evt);
            }
        });
        cbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgenderActionPerformed(evt);
            }
        });
        jPanel1.add(cbgender);
        cbgender.setBounds(190, 380, 200, 50);
        jPanel1.add(datePicker2);
        datePicker2.setBounds(410, 380, 200, 50);

        txtpassword.setText("Password");
        txtpassword.setCornerRadius(50);
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtpassword);
        txtpassword.setBounds(400, 270, 210, 40);

        myTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID#", "Username", "Name", "Score"
            }
        ));
        jScrollPane1.setViewportView(myTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 590, 240);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbgenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbgenderMouseClicked

    }//GEN-LAST:event_cbgenderMouseClicked

    private void cbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgenderActionPerformed

    }//GEN-LAST:event_cbgenderActionPerformed

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
    new txtField().checkTextField(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        new txtField().checkTextFieldEmpty(txtusername, "Username");
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
    new txtField().checkTextField(txtusername, "Username");
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
         new checkPasswordField().HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        new checkPasswordField().FocusLostPass(txtpassword, "Password");
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
         new checkPasswordField().HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
         new checkPasswordField().HoverAndClickPassword(txtpassword, chckseeUnsee, "Password");
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void chckseeUnseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeActionPerformed
       new SeeAndUnseePass().unseeAndseeIconChange(chckseeUnsee, txtpassword);
    }//GEN-LAST:event_chckseeUnseeActionPerformed

    private void txtfirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfirstnameMouseClicked
        new txtField().checkTextField(txtfirstname, "FirstName");
    }//GEN-LAST:event_txtfirstnameMouseClicked

    private void txtfirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyPressed
        new txtField().checkTextFieldEmpty(txtfirstname, "Firstname");
    }//GEN-LAST:event_txtfirstnameKeyPressed

    private void txtfirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstnameKeyReleased
new txtField().checkTextField(txtfirstname, "FirstName");
    }//GEN-LAST:event_txtfirstnameKeyReleased

    private void txtlastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyPressed
        new txtField().checkTextField(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameKeyPressed

    private void txtlastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastnameKeyReleased
        new txtField().checkTextFieldEmpty(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameKeyReleased

    private void txtlastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlastnameMouseClicked
        new txtField().checkTextField(txtlastname, "LastName");
    }//GEN-LAST:event_txtlastnameMouseClicked

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
       profile = new file().FilePictureFilter(profile);
        if(profile != null){
        new FitImage().risizelabel(profile, lblpictureHolder);
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UserInterface.CustomComponents.MyButton btnban;
    private UserInterface.CustomComponents.MyButton btndelete;
    private UserInterface.CustomComponents.MyButton btnupdate;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JCheckBox chckseeUnsee;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpictureHolder;
    private UserInterface.CustomComponents.MyButton myButton1;
    private UserInterface.CustomComponents.MyButton myButton2;
    private UserInterface.CustomComponents.MyTable myTable1;
    private UserInterface.CustomComponents.MyTextField txtfirstname;
    private UserInterface.CustomComponents.MyTextField txtlastname;
    private UserInterface.CustomComponents.MyPasswordField txtpassword;
    private UserInterface.CustomComponents.MyTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
