/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import Function.Image.FitImage;
import Function.SeeAndUnseePass.SeeAndUnseePass;
import Function.file.file;
import Function.password.checkPasswordField;
import Function.textField.txtField;
import java.io.File;

/**
 *
 * @author Admin
 */
public class Accounts extends javax.swing.JPanel {
 File profile = null;
 
    public Accounts() {
        initComponents();
          txtpassword.setEchoChar((char)0);
        btnban.setVisible(false);
        btndelete.setVisible(false);
        btnupdate.setVisible(false);
        this.datePicker2.getComponentDateTextField().setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        myTable1 = new UserInterface.CustomComponents.MyTable();
        jPanel2 = new javax.swing.JPanel();
        txtlastname = new UserInterface.CustomComponents.MyTextField();
        chckseeUnsee = new javax.swing.JCheckBox();
        cbgender = new javax.swing.JComboBox<>();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        txtfirstname = new UserInterface.CustomComponents.MyTextField();
        txtusername = new UserInterface.CustomComponents.MyTextField();
        myButton1 = new UserInterface.CustomComponents.MyButton();
        lblpictureHolder = new javax.swing.JLabel();
        txtpassword = new UserInterface.CustomComponents.MyPasswordField();
        jPanel3 = new javax.swing.JPanel();
        myButton2 = new UserInterface.CustomComponents.MyButton();
        btnupdate = new UserInterface.CustomComponents.MyButton();
        btndelete = new UserInterface.CustomComponents.MyButton();
        btnban = new UserInterface.CustomComponents.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(621, 570));

        myTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID#", "Username", "Name", "Score"
            }
        ));
        jScrollPane1.setViewportView(myTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtlastname.setText("LastName");
        txtlastname.setRadius(50);

        chckseeUnsee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", " " }));

        txtfirstname.setText("FirstName");
        txtfirstname.setRadius(50);

        txtusername.setText("Username");
        txtusername.setRadius(50);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic.png"))); // NOI18N

        lblpictureHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtpassword.setText("Password");
        txtpassword.setCornerRadius(50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chckseeUnsee))
                    .addComponent(txtlastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(chckseeUnsee, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 30));

        myButton2.setText("Add Account");
        myButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        myButton2.setRadius(50);
        jPanel3.add(myButton2);

        btnupdate.setText("Update Account");
        btnupdate.setBorderColor(new java.awt.Color(102, 204, 0));
        btnupdate.setColor(new java.awt.Color(102, 204, 0));
        btnupdate.setColorClick(new java.awt.Color(153, 255, 51));
        btnupdate.setColorOver(new java.awt.Color(153, 255, 102));
        btnupdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnupdate.setRadius(50);
        jPanel3.add(btnupdate);

        btndelete.setText("Delete Account");
        btndelete.setBorderColor(new java.awt.Color(255, 0, 0));
        btndelete.setColor(new java.awt.Color(255, 0, 0));
        btndelete.setColorClick(new java.awt.Color(255, 51, 51));
        btndelete.setColorOver(new java.awt.Color(255, 102, 102));
        btndelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndelete.setRadius(50);
        jPanel3.add(btndelete);

        btnban.setText("Ban Account");
        btnban.setBorderColor(new java.awt.Color(255, 102, 0));
        btnban.setColor(new java.awt.Color(255, 102, 0));
        btnban.setColorClick(new java.awt.Color(255, 204, 51));
        btnban.setColorOver(new java.awt.Color(255, 204, 102));
        btnban.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnban.setRadius(50);
        jPanel3.add(btnban);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private UserInterface.CustomComponents.MyButton btnban;
    private UserInterface.CustomComponents.MyButton btndelete;
    private UserInterface.CustomComponents.MyButton btnupdate;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JCheckBox chckseeUnsee;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpictureHolder;
    private UserInterface.CustomComponents.MyButton myButton1;
    private UserInterface.CustomComponents.MyButton myButton2;
    private UserInterface.CustomComponents.MyTable myTable1;
    private UserInterface.CustomComponents.MyTextField txtfirstname;
    private UserInterface.CustomComponents.MyTextField txtlastname;
    private UserInterface.CustomComponents.MyPasswordField txtpassword;
    private UserInterface.CustomComponents.MyTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
