/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UserInterface.DeletedDatas;

import Function.Image.FitImage;
import Function.SeeAndUnseePass.SeeAndUnseePass;
import Function.password.checkPasswordField;
import Function.textField.txtField;
import Model.DataManager.DataManager;
import Model.UserData.UserData;
import UserInterface.Admin.Accounts;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DeletedData extends javax.swing.JDialog {

    DataManager data = DataManager.getInstance();
    File profile = null;
    private final txtField txt = new txtField();
    private UserData user = new UserData();
    private Accounts acc = Accounts.getInstance();
    int userIndex = -1;

    public DeletedData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        user.addDataAccountTable(data.getDeletedAccounts(), myTable1);
        txtpassword.setEchoChar((char) 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myTable1 = new UserInterface.CustomComponents.MyTable();
        jPanel2 = new javax.swing.JPanel();
        txtpassword = new UserInterface.CustomComponents.MyPasswordField();
        txtlastname = new UserInterface.CustomComponents.MyTextField();
        cbgender = new javax.swing.JComboBox<>();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        txtfirstname = new UserInterface.CustomComponents.MyTextField();
        txtusername = new UserInterface.CustomComponents.MyTextField();
        lblpictureHolder = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnrestoryaccount = new UserInterface.CustomComponents.MyButton();
        btnpernadelete = new UserInterface.CustomComponents.MyButton();
        deleteall = new UserInterface.CustomComponents.MyButton();
        txtsearch = new UserInterface.CustomComponents.MyTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(621, 570));

        myTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID#", "Username", "Name", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        myTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(myTable1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtpassword.setText("Password");
        txtpassword.setToolTipText("");
        txtpassword.setCornerRadius(50);
        txtpassword.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/password.png"))); // NOI18N
        txtpassword.setEnabled(false);
        txtpassword.setName("txtpassword"); // NOI18N
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });

        txtlastname.setText("LastName");
        txtlastname.setEnabled(false);
        txtlastname.setRadius(50);
        txtlastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtlastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtlastnameFocusLost(evt);
            }
        });
        txtlastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastnameMouseClicked(evt);
            }
        });

        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));
        cbgender.setEnabled(false);
        cbgender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgenderItemStateChanged(evt);
            }
        });

        datePicker2.setEnabled(false);

        txtfirstname.setText("FirstName");
        txtfirstname.setEnabled(false);
        txtfirstname.setRadius(50);
        txtfirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfirstnameFocusLost(evt);
            }
        });
        txtfirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfirstnameMouseClicked(evt);
            }
        });

        txtusername.setText("Username");
        txtusername.setEnabled(false);
        txtusername.setRadius(50);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        lblpictureHolder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblpictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbgender, 0, 219, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))))
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblpictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 30));

        btnrestoryaccount.setText("Restore Account");
        btnrestoryaccount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnrestoryaccount.setRadius(50);
        btnrestoryaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestoryaccountActionPerformed(evt);
            }
        });
        jPanel4.add(btnrestoryaccount);

        btnpernadelete.setText("Pernament Delete Account");
        btnpernadelete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnpernadelete.setRadius(50);
        btnpernadelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpernadeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnpernadelete);

        deleteall.setText("Delete All Account");
        deleteall.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deleteall.setRadius(50);
        deleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteallActionPerformed(evt);
            }
        });
        jPanel4.add(deleteall);

        txtsearch.setText("Search");
        txtsearch.setCustomIcon1(new javax.swing.ImageIcon(getClass().getResource("/image/3741750_bussiness_ecommerce_marketplace_onlinestore_search_icon (1).png"))); // NOI18N
        txtsearch.setRadius(40);
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchFocusLost(evt);
            }
        });
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void myTable1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        int row = myTable1.getSelectedRow();
        int col = 1;//get the value in the index 1
        String selectedUsername = (String) myTable1.getValueAt(row, col);
        userIndex = new UserData().findUserIndex(data.getDeletedAccounts(), selectedUsername);
        user = data.getDeletedAccounts().get(userIndex);
        if (row != -1) {
            txtusername.setText(selectedUsername);
            txtfirstname.setText(user.getFirstName());
            txtlastname.setText(user.getLastName());
            datePicker2.setText(user.getBOD());
            cbgender.setSelectedItem(user.getGender());
            profile = user.getProfile();
            new FitImage().risizelabel(profile, lblpictureHolder);

        }
    }                                     

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {                                        
    }                                       

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {                                      
    }                                     

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                            

    }                                           

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {                                       
    }                                      

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {                                        
    }                                       

    private void txtlastnameFocusGained(java.awt.event.FocusEvent evt) {                                        
    }                                       

    private void txtlastnameFocusLost(java.awt.event.FocusEvent evt) {                                      
    }                                     

    private void txtlastnameMouseClicked(java.awt.event.MouseEvent evt) {                                         
    }                                        

    private void cbgenderItemStateChanged(java.awt.event.ItemEvent evt) {                                          

    }                                         

    private void txtfirstnameFocusGained(java.awt.event.FocusEvent evt) {                                         
    }                                        

    private void txtfirstnameFocusLost(java.awt.event.FocusEvent evt) {                                       
    }                                      

    private void txtfirstnameMouseClicked(java.awt.event.MouseEvent evt) {                                          
    }                                         

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {                                        
    }                                       

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {                                      
    }                                     

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {                                         
    }                                        

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {                                            
    }                                           

    private void deleteallActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int choose = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE ALL THE DATA PERMENANTLY ?", "DELETE ALL DATA", JOptionPane.YES_NO_OPTION);

        if (choose == JOptionPane.YES_OPTION) {
            data.getDeletedAccounts().clear();
            user.addDataAccountTable(data.getDeletedAccounts(), myTable1);
            resetInputData();
            JOptionPane.showMessageDialog(null, "SUCCESSFULLY DELETED THE DATA ", "DELETED", JOptionPane.INFORMATION_MESSAGE);

        }
    }                                         

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {                                      
        txt.checkTextField(txtsearch, "Search");
    }                                     

    private void txtsearchFocusLost(java.awt.event.FocusEvent evt) {                                    
        txt.checkTextFieldEmpty(txtsearch, "Search");
    }                                   

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {                                       
        txt.checkTextField(txtsearch, "Search");
    }                                      

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new UserData().filterAccount(data.getDeletedAccounts(), myTable1, txtsearch.getText());
    }                                         

    private void btnrestoryaccountActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        if (userIndex == -1) {
            JOptionPane.showMessageDialog(null, "PLEASE SELECT A DATA TO RESTORT TO ", "PLEASE SELETE DATA", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int choose = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT THIS ACCOUT TO RESTORT " + data.getDeletedAccounts().get(userIndex).getUsername(), "RESTORE ACCOUNT", JOptionPane.YES_NO_OPTION);

        if (choose != JOptionPane.YES_OPTION) {
            return;
        }

        JOptionPane.showMessageDialog(null, "SUCCESSFULLY RESTORE ", "RESTORE", JOptionPane.INFORMATION_MESSAGE);
        data.addUser(data.getDeletedAccounts().get(userIndex));
        data.getDeletedAccounts().remove(userIndex);
        acc.updateData();
        resetInputData();
        user.addDataAccountTable(data.getDeletedAccounts(), myTable1);


    }                                                 

    private void resetInputData() {
        txtusername.setText("Username");
        txtfirstname.setText("FirstName");
        txtlastname.setText("LastName");
        datePicker2.getComponentDateTextField().setText("");
        cbgender.insertItemAt("Gender", 0);
        cbgender.setSelectedIndex(0);
        profile = null;
        lblpictureHolder.setIcon(null);
        txtpassword.setText("Password");
    }

    private void btnpernadeleteActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (userIndex == -1) {
            JOptionPane.showMessageDialog(null, "PLEASE SELECT A DATA TO RESTORT TO ", "PLEASE SELETE DATA", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int choose = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT THIS ACCOUT TO PERNAMENTLY DELETED " + data.getDeletedAccounts().get(userIndex).getUsername(), "RESTORE ACCOUNT", JOptionPane.YES_NO_OPTION);

        if (choose == JOptionPane.YES_OPTION) {
            data.getDeletedAccounts().remove(userIndex);
            user.addDataAccountTable(data.getDeletedAccounts(), myTable1);
            resetInputData();
        }

    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletedData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletedData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletedData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletedData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeletedData dialog = new DeletedData(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private UserInterface.CustomComponents.MyButton btnpernadelete;
    private UserInterface.CustomComponents.MyButton btnrestoryaccount;
    private javax.swing.JComboBox<String> cbgender;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private UserInterface.CustomComponents.MyButton deleteall;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpictureHolder;
    private UserInterface.CustomComponents.MyTable myTable1;
    private UserInterface.CustomComponents.MyTextField txtfirstname;
    private UserInterface.CustomComponents.MyTextField txtlastname;
    private UserInterface.CustomComponents.MyPasswordField txtpassword;
    private UserInterface.CustomComponents.MyTextField txtsearch;
    private UserInterface.CustomComponents.MyTextField txtusername;
    // End of variables declaration                   
}
