/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface.User;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {
    
    public void labelHover(JLabel lbl){
    lbl.setForeground(Color.black);
    lbl.setFont(new java.awt.Font("Retro Gaming", 1, 41)); // NOI18N
    }
    
    public void labelHoverOut(JLabel lbl){
    lbl.setForeground(Color.white);
    lbl.setFont(new java.awt.Font("Retro Gaming", 0, 40)); // NOI18N
    }
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblplay = new javax.swing.JLabel();
        lblprofile = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        lblsettings = new javax.swing.JLabel();
        lblleaderboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        lblplay.setFont(new java.awt.Font("Retro Gaming", 0, 40)); // NOI18N
        lblplay.setForeground(new java.awt.Color(255, 255, 255));
        lblplay.setText("PLAY");
        lblplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblplayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblplayMouseExited(evt);
            }
        });

        lblprofile.setFont(new java.awt.Font("Retro Gaming", 0, 40)); // NOI18N
        lblprofile.setForeground(new java.awt.Color(255, 255, 255));
        lblprofile.setText("PROFILE");
        lblprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblprofileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblprofileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblprofileMouseExited(evt);
            }
        });

        lbllogout.setFont(new java.awt.Font("Retro Gaming", 0, 40)); // NOI18N
        lbllogout.setForeground(new java.awt.Color(255, 255, 255));
        lbllogout.setText("LOGOUT");
        lbllogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogoutMouseExited(evt);
            }
        });

        lblsettings.setFont(new java.awt.Font("Retro Gaming", 0, 40)); // NOI18N
        lblsettings.setForeground(new java.awt.Color(255, 255, 255));
        lblsettings.setText("SETTINGS");
        lblsettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsettingsMouseExited(evt);
            }
        });

        lblleaderboard.setFont(new java.awt.Font("Retro Gaming", 0, 38)); // NOI18N
        lblleaderboard.setForeground(new java.awt.Color(255, 255, 255));
        lblleaderboard.setText("LEADERBOARDS");
        lblleaderboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblleaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblleaderboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblleaderboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblleaderboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblplay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblprofile)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbllogout)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblsettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblleaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(lblplay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblprofile)
                .addGap(18, 18, 18)
                .addComponent(lblsettings)
                .addGap(18, 18, 18)
                .addComponent(lblleaderboard)
                .addGap(18, 18, 18)
                .addComponent(lbllogout)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblplayMouseEntered
      labelHover(lblplay);
    }//GEN-LAST:event_lblplayMouseEntered

    private void lblplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblplayMouseClicked
      labelHoverOut(lblplay);
    }//GEN-LAST:event_lblplayMouseClicked

    private void lblplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblplayMouseExited
        labelHoverOut(lblplay);
    }//GEN-LAST:event_lblplayMouseExited

    private void lblprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprofileMouseClicked
           labelHoverOut(lblprofile);
    }//GEN-LAST:event_lblprofileMouseClicked

    private void lblprofileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprofileMouseEntered
        labelHover(lblprofile);
    }//GEN-LAST:event_lblprofileMouseEntered

    private void lblprofileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprofileMouseExited
        labelHoverOut(lblprofile);
    }//GEN-LAST:event_lblprofileMouseExited

    private void lblsettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsettingsMouseClicked
     labelHoverOut(lblsettings);
    }//GEN-LAST:event_lblsettingsMouseClicked

    private void lblsettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsettingsMouseEntered
            labelHover(lblsettings);
    }//GEN-LAST:event_lblsettingsMouseEntered

    private void lblsettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsettingsMouseExited
            labelHoverOut(lblsettings);
    }//GEN-LAST:event_lblsettingsMouseExited

    private void lblleaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblleaderboardMouseClicked
            labelHoverOut(lblleaderboard);
    }//GEN-LAST:event_lblleaderboardMouseClicked

    private void lblleaderboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblleaderboardMouseEntered
           labelHover(lblleaderboard);
    }//GEN-LAST:event_lblleaderboardMouseEntered

    private void lblleaderboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblleaderboardMouseExited
            labelHoverOut(lblleaderboard);
    }//GEN-LAST:event_lblleaderboardMouseExited

    private void lbllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseClicked
            labelHoverOut(lbllogout);
    }//GEN-LAST:event_lbllogoutMouseClicked

    private void lbllogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseEntered
            labelHover(lbllogout);
    }//GEN-LAST:event_lbllogoutMouseEntered

    private void lbllogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogoutMouseExited
                labelHoverOut(lbllogout);
    }//GEN-LAST:event_lbllogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblleaderboard;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblplay;
    private javax.swing.JLabel lblprofile;
    private javax.swing.JLabel lblsettings;
    // End of variables declaration//GEN-END:variables
}
