/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UserInterface.changedata;

import Function.textField.txtField;
import Model.DataManager.DataManager;
import Model.UserData.UserData;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChangeUser extends javax.swing.JDialog {
    DataManager data = DataManager.getInstance();
    private static int userIndex;

    private void changeUser() {
        String oldUser = txtOldUsername.getText();
        String newUser = txtNewUsername.getText();
        String ConfrimNewUser = txtConfrimNewUsername.getText();
        UserData us = data.getData().get(userIndex);
        if (oldUser.isEmpty() || oldUser.equals("Old Username")
                || newUser.equals("New Username") || newUser.isEmpty()
                || ConfrimNewUser.equals("Confirm New Password") || ConfrimNewUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "INVALID UPDATE PLEASE FILL UP ALL THE DATA", "INVALID UPDATE", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!oldUser.equals(us.getUsername())) {
            JOptionPane.showMessageDialog(null, "THE CURRENT CURRENT USERNAME DIDNT MATCH", "DIDNT MATCH", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (!newUser.equals(ConfrimNewUser)) {
            JOptionPane.showMessageDialog(null, "THE NEW AND CONFIRM DIDNT MATCH PLEASE MATCH IT", "DIDNT MATCH", JOptionPane.INFORMATION_MESSAGE);

            return;
        }
us.setUsername(newUser); 
JOptionPane.showMessageDialog(null, "Username updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    public ChangeUser(java.awt.Frame parent, boolean modal, int userIndex) {
        super(parent, modal);
        initComponents();
        this.userIndex = userIndex;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNewPassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnChangeUsername = new UserInterface.CustomComponents.MyButton();
        txtConfrimNewUsername = new UserInterface.CustomComponents.MyTextField();
        txtOldUsername = new UserInterface.CustomComponents.MyTextField();
        txtNewUsername = new UserInterface.CustomComponents.MyTextField();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Old Username");
        bodyPanel.add(jLabel2);
        jLabel2.setBounds(22, 27, 120, 18);

        lblNewPassword.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblNewPassword.setText("New Username");
        bodyPanel.add(lblNewPassword);
        lblNewPassword.setBounds(22, 99, 125, 18);

        jLabel4.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Confirm Username");
        bodyPanel.add(jLabel4);
        jLabel4.setBounds(22, 177, 158, 18);

        btnChangeUsername.setText("Change Username");
        btnChangeUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangeUsername.setRadius(50);
        btnChangeUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUsernameActionPerformed(evt);
            }
        });
        bodyPanel.add(btnChangeUsername);
        btnChangeUsername.setBounds(352, 265, 174, 39);

        txtConfrimNewUsername.setText("Confirm New Username");
        txtConfrimNewUsername.setRadius(50);
        txtConfrimNewUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfrimNewUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfrimNewUsernameFocusLost(evt);
            }
        });
        txtConfrimNewUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConfrimNewUsernameMouseClicked(evt);
            }
        });
        txtConfrimNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfrimNewUsernameActionPerformed(evt);
            }
        });
        bodyPanel.add(txtConfrimNewUsername);
        txtConfrimNewUsername.setBounds(20, 200, 290, 50);

        txtOldUsername.setText("Old Username");
        txtOldUsername.setRadius(50);
        txtOldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOldUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOldUsernameFocusLost(evt);
            }
        });
        txtOldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOldUsernameMouseClicked(evt);
            }
        });
        txtOldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldUsernameActionPerformed(evt);
            }
        });
        bodyPanel.add(txtOldUsername);
        txtOldUsername.setBounds(20, 50, 290, 50);

        txtNewUsername.setText("New Username");
        txtNewUsername.setRadius(50);
        txtNewUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewUsernameFocusLost(evt);
            }
        });
        txtNewUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewUsernameMouseClicked(evt);
            }
        });
        txtNewUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUsernameActionPerformed(evt);
            }
        });
        bodyPanel.add(txtNewUsername);
        txtNewUsername.setBounds(20, 120, 290, 50);

        headerPanel.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel1.setText("Change Username");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUsernameActionPerformed
        changeUser();
    }//GEN-LAST:event_btnChangeUsernameActionPerformed

    private void txtOldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldUsernameActionPerformed
        changeUser();
    }//GEN-LAST:event_txtOldUsernameActionPerformed

    private void txtNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUsernameActionPerformed
        changeUser();
    }//GEN-LAST:event_txtNewUsernameActionPerformed

    private void txtConfrimNewUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfrimNewUsernameActionPerformed
        changeUser();
    }//GEN-LAST:event_txtConfrimNewUsernameActionPerformed

    private void txtOldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldUsernameFocusGained
        new txtField().checkTextField(txtOldUsername, "Old Username");
    }//GEN-LAST:event_txtOldUsernameFocusGained

    private void txtOldUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldUsernameFocusLost
        new txtField().checkTextFieldEmpty(txtOldUsername, "Old Username");
    }//GEN-LAST:event_txtOldUsernameFocusLost

    private void txtOldUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOldUsernameMouseClicked
        new txtField().checkTextField(txtOldUsername, "Old Username");
    }//GEN-LAST:event_txtOldUsernameMouseClicked

    private void txtNewUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewUsernameFocusGained
        new txtField().checkTextField(txtNewUsername, "New Username");
    }//GEN-LAST:event_txtNewUsernameFocusGained

    private void txtNewUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewUsernameFocusLost
        new txtField().checkTextFieldEmpty(txtNewUsername, "Old Username");
    }//GEN-LAST:event_txtNewUsernameFocusLost

    private void txtNewUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewUsernameMouseClicked
        new txtField().checkTextField(txtNewUsername, "New Username");
    }//GEN-LAST:event_txtNewUsernameMouseClicked

    private void txtConfrimNewUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfrimNewUsernameFocusGained
        new txtField().checkTextField(txtConfrimNewUsername, "Confrim New Username");
    }//GEN-LAST:event_txtConfrimNewUsernameFocusGained

    private void txtConfrimNewUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfrimNewUsernameFocusLost
        new txtField().checkTextFieldEmpty(txtConfrimNewUsername, "Old Username");
    }//GEN-LAST:event_txtConfrimNewUsernameFocusLost

    private void txtConfrimNewUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConfrimNewUsernameMouseClicked
        new txtField().checkTextField(txtConfrimNewUsername, "Confrim New Username");
    }//GEN-LAST:event_txtConfrimNewUsernameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeUser dialog = new ChangeUser(new javax.swing.JFrame(), true, userIndex);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private UserInterface.CustomComponents.MyButton btnChangeUsername;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNewPassword;
    private UserInterface.CustomComponents.MyTextField txtConfrimNewUsername;
    private UserInterface.CustomComponents.MyTextField txtNewUsername;
    private UserInterface.CustomComponents.MyTextField txtOldUsername;
    // End of variables declaration//GEN-END:variables
}
