/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UserInterface.changedata;

import Function.password.checkPasswordField;
import Model.UserData.UserData;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChangePass extends javax.swing.JDialog {

    private checkPasswordField chckpass = new checkPasswordField();

    private static ArrayList<UserData> data;
    private static int userIndex;

    private void changePass() {
        UserData us = data.get(userIndex);
        String oldPass = us.userPasswordHash(txtOldpass.getPassword().toString());
        String newPass = txtNewpass.getPassword().toString();
        String confirmNewPass = txtnewConfirmPass.getPassword().toString();
        if (txtOldpass.getPassword().toString().equals("Old Password") || txtOldpass.getPassword().toString().isEmpty()
                || newPass.isEmpty() || newPass.equals("New Password")
                || confirmNewPass.isEmpty() || confirmNewPass.equals("Confirm New Password")) {
                        JOptionPane.showMessageDialog(null, "INVALID UPDATE PLEASE FILL ALL THE DATA ", "NO DATA TO UPDATE", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!us.getPassword().equals(oldPass)) {
            JOptionPane.showMessageDialog(null, "THE CURRENT PASSWORD DIDNT MATCH", "PASSWORD DIDNT MATCH", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (!new checkPasswordField().isConfirmPassAndPassSame(newPass, confirmNewPass)) {
            JOptionPane.showMessageDialog(null, "THE NEW PASSWORD DIDNT MATCH TO THE CONFRIM PASSWORD", "PASSWORD DIDNT MATCH", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        us.updatePassword(data, userIndex, newPass);
        JOptionPane.showMessageDialog(null, "SUCCESSFULL UPDATE THE PASSWORD", "SUCCESSFULYY UPDATED", JOptionPane.INFORMATION_MESSAGE);

    }

    public ChangePass(java.awt.Frame parent, boolean modal, ArrayList<UserData> data, int userIndex) {
        super(parent, modal);
        initComponents();
        this.userIndex = userIndex;
        this.data = data;
        txtNewpass.setEchoChar((char) 0);
        txtOldpass.setEchoChar((char) 0);
        txtnewConfirmPass.setEchoChar((char) 0);
        this.chckseeUnseeConfirmPass.setVisible(false);
        this.chckseeUnseeNewPass.setVisible(false);
        this.chckseeUnseeOldPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chckseeUnseeOldPass = new javax.swing.JCheckBox();
        chckseeUnseeNewPass = new javax.swing.JCheckBox();
        chckseeUnseeConfirmPass = new javax.swing.JCheckBox();
        txtOldpass = new UserInterface.CustomComponents.MyPasswordField();
        txtNewpass = new UserInterface.CustomComponents.MyPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        txtnewConfirmPass = new UserInterface.CustomComponents.MyPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnChangePass = new UserInterface.CustomComponents.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Retro Gaming", 0, 24)); // NOI18N
        jLabel1.setText("Change Password");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Old Password");
        bodyPanel.add(jLabel2);
        jLabel2.setBounds(22, 27, 120, 18);

        chckseeUnseeOldPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnseeOldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeOldPassActionPerformed(evt);
            }
        });
        bodyPanel.add(chckseeUnseeOldPass);
        chckseeUnseeOldPass.setBounds(230, 70, 24, 20);

        chckseeUnseeNewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnseeNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeNewPassActionPerformed(evt);
            }
        });
        bodyPanel.add(chckseeUnseeNewPass);
        chckseeUnseeNewPass.setBounds(230, 140, 24, 20);

        chckseeUnseeConfirmPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/see.png"))); // NOI18N
        chckseeUnseeConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckseeUnseeConfirmPassActionPerformed(evt);
            }
        });
        bodyPanel.add(chckseeUnseeConfirmPass);
        chckseeUnseeConfirmPass.setBounds(230, 220, 24, 20);

        txtOldpass.setText("Old Password");
        txtOldpass.setCornerRadius(50);
        txtOldpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOldpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOldpassFocusLost(evt);
            }
        });
        txtOldpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOldpassMouseClicked(evt);
            }
        });
        txtOldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldpassActionPerformed(evt);
            }
        });
        txtOldpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOldpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOldpassKeyReleased(evt);
            }
        });
        bodyPanel.add(txtOldpass);
        txtOldpass.setBounds(22, 57, 245, 36);

        txtNewpass.setText("New Password");
        txtNewpass.setCornerRadius(50);
        txtNewpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewpassFocusLost(evt);
            }
        });
        txtNewpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewpassMouseClicked(evt);
            }
        });
        txtNewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewpassActionPerformed(evt);
            }
        });
        txtNewpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewpassKeyReleased(evt);
            }
        });
        bodyPanel.add(txtNewpass);
        txtNewpass.setBounds(22, 129, 245, 36);

        lblNewPassword.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        lblNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblNewPassword.setText("New Password");
        bodyPanel.add(lblNewPassword);
        lblNewPassword.setBounds(22, 99, 125, 18);

        txtnewConfirmPass.setText("Confirm New Password");
        txtnewConfirmPass.setCornerRadius(50);
        txtnewConfirmPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnewConfirmPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnewConfirmPassFocusLost(evt);
            }
        });
        txtnewConfirmPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnewConfirmPassMouseClicked(evt);
            }
        });
        txtnewConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewConfirmPassActionPerformed(evt);
            }
        });
        txtnewConfirmPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnewConfirmPassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewConfirmPassKeyReleased(evt);
            }
        });
        bodyPanel.add(txtnewConfirmPass);
        txtnewConfirmPass.setBounds(22, 207, 245, 36);

        jLabel4.setFont(new java.awt.Font("Retro Gaming", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Confirm New Password");
        bodyPanel.add(jLabel4);
        jLabel4.setBounds(22, 177, 196, 18);

        btnChangePass.setText("Change Password");
        btnChangePass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangePass.setRadius(50);
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        bodyPanel.add(btnChangePass);
        btnChangePass.setBounds(352, 265, 174, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chckseeUnseeOldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeOldPassActionPerformed

    }//GEN-LAST:event_chckseeUnseeOldPassActionPerformed

    private void chckseeUnseeNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chckseeUnseeNewPassActionPerformed

    private void chckseeUnseeConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckseeUnseeConfirmPassActionPerformed

    }//GEN-LAST:event_chckseeUnseeConfirmPassActionPerformed

    private void txtOldpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldpassFocusGained
        chckpass.HoverAndClickPassword(txtOldpass, chckseeUnseeOldPass, "Old Password");
    }//GEN-LAST:event_txtOldpassFocusGained

    private void txtOldpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldpassFocusLost
        chckpass.FocusLostPass(txtOldpass, "Old Password");
    }//GEN-LAST:event_txtOldpassFocusLost

    private void txtOldpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOldpassMouseClicked
        chckpass.HoverAndClickPassword(txtOldpass, chckseeUnseeOldPass, "Old Password");
    }//GEN-LAST:event_txtOldpassMouseClicked

    private void txtOldpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldpassKeyPressed
        chckpass.HoverAndClickPassword(txtOldpass, chckseeUnseeOldPass, "Old Password");
    }//GEN-LAST:event_txtOldpassKeyPressed

    private void txtOldpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldpassKeyReleased
        chckpass.HoverAndClickPassword(txtOldpass, chckseeUnseeOldPass, "Old Password");
    }//GEN-LAST:event_txtOldpassKeyReleased

    private void txtNewpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewpassFocusGained
        chckpass.HoverAndClickPassword(txtNewpass, chckseeUnseeNewPass, "New Password");
    }//GEN-LAST:event_txtNewpassFocusGained

    private void txtNewpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewpassFocusLost
        chckpass.FocusLostPass(txtNewpass, "New Password");
    }//GEN-LAST:event_txtNewpassFocusLost

    private void txtNewpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewpassMouseClicked
        chckpass.HoverAndClickPassword(txtNewpass, chckseeUnseeNewPass, "New Password");
    }//GEN-LAST:event_txtNewpassMouseClicked

    private void txtNewpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewpassKeyPressed
        chckpass.HoverAndClickPassword(txtNewpass, chckseeUnseeNewPass, "New Password");
    }//GEN-LAST:event_txtNewpassKeyPressed

    private void txtNewpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewpassKeyReleased
        chckpass.HoverAndClickPassword(txtNewpass, chckseeUnseeNewPass, "New Password");
    }//GEN-LAST:event_txtNewpassKeyReleased

    private void txtnewConfirmPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewConfirmPassFocusGained
        chckpass.HoverAndClickPassword(txtnewConfirmPass, chckseeUnseeConfirmPass, "Confrim New Password");
    }//GEN-LAST:event_txtnewConfirmPassFocusGained

    private void txtnewConfirmPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewConfirmPassFocusLost
        chckpass.FocusLostPass(txtnewConfirmPass, "Confirm New Password");
    }//GEN-LAST:event_txtnewConfirmPassFocusLost

    private void txtnewConfirmPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnewConfirmPassMouseClicked
        chckpass.HoverAndClickPassword(txtnewConfirmPass, chckseeUnseeConfirmPass, "Confirm New Password");
    }//GEN-LAST:event_txtnewConfirmPassMouseClicked

    private void txtnewConfirmPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewConfirmPassKeyPressed
        chckpass.HoverAndClickPassword(txtnewConfirmPass, chckseeUnseeConfirmPass, "Confirm Old Password");
    }//GEN-LAST:event_txtnewConfirmPassKeyPressed

    private void txtnewConfirmPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewConfirmPassKeyReleased
        chckpass.HoverAndClickPassword(txtnewConfirmPass, chckseeUnseeConfirmPass, "Confirm Old Password");
    }//GEN-LAST:event_txtnewConfirmPassKeyReleased

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
       changePass();
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void txtOldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldpassActionPerformed
        changePass();
    }//GEN-LAST:event_txtOldpassActionPerformed

    private void txtNewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewpassActionPerformed
        changePass();
    }//GEN-LAST:event_txtNewpassActionPerformed

    private void txtnewConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewConfirmPassActionPerformed
        changePass();
    }//GEN-LAST:event_txtnewConfirmPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePass dialog = new ChangePass(new javax.swing.JFrame(), true, data, userIndex);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private UserInterface.CustomComponents.MyButton btnChangePass;
    private javax.swing.JCheckBox chckseeUnseeConfirmPass;
    private javax.swing.JCheckBox chckseeUnseeNewPass;
    private javax.swing.JCheckBox chckseeUnseeOldPass;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblNewPassword;
    private UserInterface.CustomComponents.MyPasswordField txtNewpass;
    private UserInterface.CustomComponents.MyPasswordField txtOldpass;
    private UserInterface.CustomComponents.MyPasswordField txtnewConfirmPass;
    // End of variables declaration//GEN-END:variables
}
